module.exports = [
  {
    disable: "disabled",
    month: "Sep",
    dd: "28",
    sup: "th",
    startDay: "Sat",
    endDay: "- Sun",
    numberOfDays: "(18 Days)",
    weekEnd: "Weekend Batch",
    batchStatusIcon: "",
    batchStatus: "Sold Out",
    startTime: " 07:00 AM",
    endTime: "09:00 AM (IST)",
  },
  {
    disable: "",
    month: "Oct",
    dd: "15",
    sup: "th",
    startDay: "Thr",
    endDay: "- Fri",
    numberOfDays: "(18 Days)",
    weekEnd: "",
    batchStatusIcon: "Fast_Filling",
    batchStatus: "Fast_Filling",
    startTime: " 07:00 AM",
    endTime: "09:00 AM (IST)",
  },
  {
    disable: "",
    month: "Oct",
    dd: "24",
    sup: "th",
    startDay: "Sat",
    endDay: "- Sun",
    numberOfDays: "(6 Week)",
    weekEnd: "Weekend Batch",
    batchStatusIcon: "",
    batchStatus: "",
    startTime: " 08:30 PM",
    endTime: "11:30 PM (IST)",
  },
  {
    disable: "",
    month: "Oct",
    dd: "26",
    sup: "th",
    startDay: "Mon",
    endDay: "- Fri",
    numberOfDays: "(18 Days)",
    weekEnd: "",
    batchStatusIcon: "",
    batchStatus: "",
    startTime: " 08:30 PM",
    endTime: "10:30 PM (IST)",
  },
];
